package ir.k1adili.projectcam.ui.theme

import androidx.compose.ui.graphics.Color

// Seed: Caterpillar yellow - the brand color of heavy construction/civil-engineering equipment.
val CatYellow = Color(0xFFFFCD11)

val LightPrimary = Color(0xFFFFCD11)
val LightOnPrimary = Color(0xFF231C00)
val LightPrimaryContainer = Color(0xFFFFF3B0)
val LightOnPrimaryContainer = Color(0xFF3A2E00)
val LightSecondary = Color(0xFF4A4A4A)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE3E1D6)
val LightOnSecondaryContainer = Color(0xFF1A1A1A)
val LightBackground = Color(0xFFFFFBEE)
val LightOnBackground = Color(0xFF1C1B13)
val LightSurface = Color(0xFFFFFBEE)
val LightOnSurface = Color(0xFF1C1B13)
val LightSurfaceVariant = Color(0xFFF0E6C2)
val LightOnSurfaceVariant = Color(0xFF4D4632)
val LightOutline = Color(0xFF807A5D)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)

val DarkPrimary = Color(0xFFFFD54A)
val DarkOnPrimary = Color(0xFF3A2E00)
val DarkPrimaryContainer = Color(0xFF574600)
val DarkOnPrimaryContainer = Color(0xFFFFE28A)
val DarkSecondary = Color(0xFFCBC3A0)
val DarkOnSecondary = Color(0xFF332D14)
val DarkSecondaryContainer = Color(0xFF4A4429)
val DarkOnSecondaryContainer = Color(0xFFE8DFB9)
val DarkBackground = Color(0xFF16150F)
val DarkOnBackground = Color(0xFFE7E2D3)
val DarkSurface = Color(0xFF16150F)
val DarkOnSurface = Color(0xFFE7E2D3)
val DarkSurfaceVariant = Color(0xFF4D4632)
val DarkOnSurfaceVariant = Color(0xFFD1C7A4)
val DarkOutline = Color(0xFF9A9377)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)

// High-signal accents used sparingly (selection states, GPS-accuracy badges)
val AccentTeal = Color(0xFF1D7A73)
val WarningAmber = Color(0xFFB8860B)
